name: Deploy React App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Install and Build
        run: |
          npm install
          npm run build

      - name: 4. Enable IPv6
        uses: fscarmen/warp-on-actions@v1.1

      - name: 5. Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: 6. Deploy to Server (Native SCP)
        run: |
          ssh -6 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -o IdentitiesOnly=yes debian@${{ secrets.SERVER_HOST }} "mkdir -p ~/flashcards"
          
          scp -6 -r -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -o IdentitiesOnly=yes dist/* debian@[${{ secrets.SERVER_HOST }}]:~/flashcards/